### ISSUE TITLE
ValueError: X has 100620 features per sample; expecting 6480

### ISSUE THREAD

**Issue by oshadaamila** [BUPTLdy/object-detector#8]
I encountered with following error
`C:\ProgramData\Anaconda3\envs\human-detector\python.exe "D:/Campus/FYP/Implementations/Codes From Github/human_detection_using_hog/human-detector/object_detector/detector.py"
C:\ProgramData\Anaconda3\envs\human-detector\lib\site-packages\sklearn\base.py:253: UserWarning: Trying to unpickle estimator LinearSVC from version pre-0.18 when using version 0.20.4. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
C:\ProgramData\Anaconda3\envs\human-detector\lib\site-packages\skimage\feature\_hog.py:150: skimage_deprecation: Default value of `block_norm`==`L1` is deprecated and will be changed to `L2-Hys` in v0.15. To supress this message specify explicitly the normalization method.
  skimage_deprecation)
Traceback (most recent call last):
  File "D:/human_detection_using_hog/human-detector/object_detector/detector.py", line 104, in <module>
    test_folder(foldername)
  File "D:/human_detection_using_hog/human-detector/object_detector/detector.py", line 100, in test_folder
    detector(filename)
  File "D:/human_detection_using_hog/human-detector/object_detector/detector.py", line 58, in detector
    pred = clf.predict(fd)
  File "C:\ProgramData\Anaconda3\envs\human-detector\lib\site-packages\sklearn\linear_model\base.py", line 281, in predict
    scores = self.decision_function(X)
  File "C:\ProgramData\Anaconda3\envs\human-detector\lib\site-packages\sklearn\linear_model\base.py", line 262, in decision_function
    % (X.shape[1], n_features))
ValueError: X has 100620 features per sample; expecting 6480
`
any guesses on how to solve this?

**Comment by fistyee** [comment]
> I encountered with following error
> `C:\ProgramData\Anaconda3\envs\human-detector\python.exe "D:/Campus/FYP/Implementations/Codes From Github/human_detection_using_hog/human-detector/object_detector/detector.py" C:\ProgramData\Anaconda3\envs\human-detector\lib\site-packages\sklearn\base.py:253: UserWarning: Trying to unpickle estimator LinearSVC from version pre-0.18 when using version 0.20.4. This might lead to breaking code or invalid results. Use at your own risk. UserWarning) C:\ProgramData\Anaconda3\envs\human-detector\lib\site-packages\skimage\feature\_hog.py:150: skimage_deprecation: Default value of `block_norm`==`L1`is deprecated and will be changed to`L2-Hys`in v0.15. To supress this message specify explicitly the normalization method. skimage_deprecation) Traceback (most recent call last): File "D:/human_detection_using_hog/human-detector/object_detector/detector.py", line 104, in <module> test_folder(foldername) File "D:/human_detection_using_hog/human-detector/object_detector/detector.py", line 100, in test_folder detector(filename) File "D:/human_detection_using_hog/human-detector/object_detector/detector.py", line 58, in detector pred = clf.predict(fd) File "C:\ProgramData\Anaconda3\envs\human-detector\lib\site-packages\sklearn\linear_model\base.py", line 281, in predict scores = self.decision_function(X) File "C:\ProgramData\Anaconda3\envs\human-detector\lib\site-packages\sklearn\linear_model\base.py", line 262, in decision_function % (X.shape[1], n_features)) ValueError: X has 100620 features per sample; expecting 6480`
> any guesses on how to solve this?

Same problem. Do you solved it?
